/*
  # Create Closed Deals Table

  ## Overview
  Table to track business deals closed between member companies.
  This tracks the networking value generated by the Confraria.

  ## Fields
  - id (uuid, PK)
  - seller_company_id (uuid, FK) - Company that sold
  - buyer_company_id (uuid, FK) - Company that bought
  - amount (decimal) - Deal value in BRL
  - description (text) - Description of the deal
  - deal_date (date) - When the deal was closed
  - registered_by (uuid, FK) - Profile who registered this deal
  - status (text) - Deal status (pending, confirmed, cancelled)
  - notes (text) - Additional notes
  - created_at, updated_at (timestamps)
*/

-- Create closed_deals table
CREATE TABLE IF NOT EXISTS public.closed_deals (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  seller_company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE RESTRICT,
  buyer_company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE RESTRICT,
  amount decimal(15, 2) NOT NULL CHECK (amount > 0),
  description text,
  deal_date date NOT NULL DEFAULT CURRENT_DATE,
  registered_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  status text NOT NULL DEFAULT 'confirmed' CHECK (status IN ('pending', 'confirmed', 'cancelled')),
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  -- Prevent company from closing deal with itself
  CONSTRAINT different_companies CHECK (seller_company_id != buyer_company_id)
);

-- Enable RLS
ALTER TABLE public.closed_deals ENABLE ROW LEVEL SECURITY;

-- RLS Policies for closed_deals

-- Authenticated users can view all confirmed deals
CREATE POLICY "Authenticated users can view confirmed deals"
  ON public.closed_deals FOR SELECT
  TO authenticated
  USING (status = 'confirmed');

-- Admins can view all deals
CREATE POLICY "Admins can view all deals"
  ON public.closed_deals FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE id = auth.uid() AND role = 'admin'
    )
  );

-- Admins can insert deals
CREATE POLICY "Admins can insert deals"
  ON public.closed_deals FOR INSERT
  TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE id = auth.uid() AND role = 'admin'
    )
  );

-- Members can insert deals (for their companies)
CREATE POLICY "Members can insert deals for their companies"
  ON public.closed_deals FOR INSERT
  TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.members m
      WHERE m.profile_id = auth.uid()
      AND m.status = 'active'
      AND (m.company_id = seller_company_id OR m.company_id = buyer_company_id)
    )
  );

-- Admins can update deals
CREATE POLICY "Admins can update deals"
  ON public.closed_deals FOR UPDATE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE id = auth.uid() AND role = 'admin'
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE id = auth.uid() AND role = 'admin'
    )
  );

-- Admins can delete deals
CREATE POLICY "Admins can delete deals"
  ON public.closed_deals FOR DELETE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE id = auth.uid() AND role = 'admin'
    )
  );

-- Indexes
CREATE INDEX IF NOT EXISTS idx_closed_deals_seller ON public.closed_deals(seller_company_id);
CREATE INDEX IF NOT EXISTS idx_closed_deals_buyer ON public.closed_deals(buyer_company_id);
CREATE INDEX IF NOT EXISTS idx_closed_deals_status ON public.closed_deals(status);
CREATE INDEX IF NOT EXISTS idx_closed_deals_deal_date ON public.closed_deals(deal_date);
CREATE INDEX IF NOT EXISTS idx_closed_deals_amount ON public.closed_deals(amount);

-- Trigger for updated_at
DROP TRIGGER IF EXISTS update_closed_deals_updated_at ON public.closed_deals;
CREATE TRIGGER update_closed_deals_updated_at
  BEFORE UPDATE ON public.closed_deals
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

-- Function to get total deals value
CREATE OR REPLACE FUNCTION public.get_total_deals_value()
RETURNS decimal
LANGUAGE sql
STABLE
SECURITY DEFINER
AS $$
  SELECT COALESCE(SUM(amount), 0)
  FROM public.closed_deals
  WHERE status = 'confirmed';
$$;
